/* Auto-generated by genmsg_cpp for file /home/ciby/ros_workspace/sande/seneka/seneka_windsensor/msg/WindData.msg */
#ifndef SENEKA_WINDSENSOR_MESSAGE_WINDDATA_H
#define SENEKA_WINDSENSOR_MESSAGE_WINDDATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace seneka_windsensor
{
template <class ContainerAllocator>
struct WindData_ {
  typedef WindData_<ContainerAllocator> Type;

  WindData_()
  : header()
  , speed(0.0)
  , direction(0.0)
  {
  }

  WindData_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , speed(0.0)
  , direction(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _speed_type;
  double speed;

  typedef double _direction_type;
  double direction;


  typedef boost::shared_ptr< ::seneka_windsensor::WindData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seneka_windsensor::WindData_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct WindData
typedef  ::seneka_windsensor::WindData_<std::allocator<void> > WindData;

typedef boost::shared_ptr< ::seneka_windsensor::WindData> WindDataPtr;
typedef boost::shared_ptr< ::seneka_windsensor::WindData const> WindDataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::seneka_windsensor::WindData_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::seneka_windsensor::WindData_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace seneka_windsensor

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::seneka_windsensor::WindData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::seneka_windsensor::WindData_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::seneka_windsensor::WindData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ded74466d35842290151727bd936be00";
  }

  static const char* value(const  ::seneka_windsensor::WindData_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xded74466d3584229ULL;
  static const uint64_t static_value2 = 0x0151727bd936be00ULL;
};

template<class ContainerAllocator>
struct DataType< ::seneka_windsensor::WindData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "seneka_windsensor/WindData";
  }

  static const char* value(const  ::seneka_windsensor::WindData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::seneka_windsensor::WindData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
# wind speed [m/s]\n\
float64 speed\n\
\n\
# wind direction [angle in radians relative to mounting position]\n\
float64 direction\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::seneka_windsensor::WindData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::seneka_windsensor::WindData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::seneka_windsensor::WindData_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::seneka_windsensor::WindData_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.speed);
    stream.next(m.direction);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct WindData_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seneka_windsensor::WindData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::seneka_windsensor::WindData_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "direction: ";
    Printer<double>::stream(s, indent + "  ", v.direction);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SENEKA_WINDSENSOR_MESSAGE_WINDDATA_H

